### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by afirth** [equinor/release-aware#12]
Hey, this is cool!
Is it open source? If so, would you be willing to license it? I'd be happy to use and contribute if it's open, like Apache 2 or MIT. Github has an easy [license adder](https://docs.github.com/en/github/building-a-strong-community/adding-a-license-to-a-repository#including-an-open-source-license-in-your-repository)

I found this too, which is similar, but in js and doesn't have the features or any container setup yet... https://github.com/halkeye/release-dashboard

**Comment by audunsolemdal** [comment]
@eoaksnes Added a license. Feel free to contribute and use it.

Note that there is some spaghetti code by myself as I don't really know Go. ;). But the app works.

Only major bug I would address is that HTTP 404 for a single repo results to the entire backend request failing.
