### ISSUE TITLE
Backend: Do not throw http 500 if repo doesn't exist

### ISSUE THREAD

**Issue by audunsolemdal** [equinor/release-aware#14]
If your list of repos or helm repos are not found, or you forget adding a comma to the list, the entire backend request failing.

Error handling should be added to the backend to:
- Show a meaningful error message, e.g. "Could not find repo "xxxx"
- If possible, ignore the 'not found' repo throwing an error.

**Comment by ShaileshSurya** [comment]
Hi @audunsolemdal Can you give some more information around this?

1. How do we reproduce this issue? I have been through the Local Setup Guide for Server. 
2. Do we have Rest-API's for this. If yes can you please help me with that. 

Also when is this changes are expected to be committed as the hackoberfest is still days away. What are the plans on this?

**Comment by audunsolemdal** [comment]
Hello @ShaileshSurya 

To reproduce, see the example in the release-aware/docker-compose.yml file
Under     environment:
      REPOSITORIES: |

Add a repo that doesn't exist or remove a comma.

Come to think of it, backend might have a cleaner display, but the frontend will display "HTTP 500", and nothing else.

**Comment by mayank271** [comment]
Hi @ShaileshSurya, are you currently working on this issue? If not, I can pick it up.

**Comment by ShaileshSurya** [comment]
@mayank271  Yes I am working on this. Planning makes the code changes in a couple of days. If you don't see any update from my side by Monday, 5th Oct. Feel free to submit a PR.

**Comment by audunsolemdal** [comment]
I have now added hacktoberfest topic to repo so your contributions should count.
